### ISSUE TITLE
Move iomb/webapi here?

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO_API#3]
If you think it is OK, I would prefer having the python version of the API in this repository, so its easier to compare and manages changes to the API. Then we could make the README about the USEEIO_API in general (I need a broader readme) and house it here.  So the proposal would be to move the two files from https://github.com/USEPA/IO-Model-Builder/tree/master/iomb/webapi into this repository, probably in a folder like 'useeioapipy'.  I suppose we could then create a simple setup.py if we wanted to make it installable.

**Comment by msrocka** [comment]
I ported the current version from the iomb module to a standalone Python module in the `python` subfolder: https://github.com/USEPA/USEEIO_API/tree/master/python

The server can be started via

```
python -m useeioapi -data ..\path\to\data\folder -port 9999
```

Maybe it would be also good to add our test suite to this module so that we have all implementations and tests in one place. It could be executed via a command like:

```
python tests\all.py -endpoint http://some.useeio.url/api -apikey some-optional-key
```

Then we can run our test suite against end-points with the Go and Python implementation and make sure that both implementations pass it.

**Comment by WesIngwersen** [comment]
OK, I agree to move the testing suite code here as well. Please proceed with that when you are ready.

**Comment by WesIngwersen** [comment]
Moved python API and tests to python folder
